# Generated by Django 2.2.7 on 2019-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='管理员ID')),
                ('name', models.CharField(max_length=100, verbose_name='管理员用户名')),
                ('password', models.CharField(max_length=100, verbose_name='管理员密码')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='企业ID')),
                ('name', models.CharField(max_length=100, verbose_name='企业用户名')),
                ('password', models.CharField(max_length=50, verbose_name='企业密码')),
                ('enterName', models.CharField(max_length=500, null=True, verbose_name='企业名称')),
                ('authState', models.IntegerField(choices=[(-1, '未审核'), (1, '审核中'), (2, '已通过'), (3, '未通过')], default=-1, verbose_name='审核状态')),
            ],
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='农民工ID')),
                ('name', models.CharField(max_length=100, verbose_name='农民工用户名')),
                ('password', models.CharField(max_length=100, verbose_name='农民工密码')),
                ('IDCard', models.CharField(max_length=100, null=True, verbose_name='农民工身份证号')),
                ('type', models.IntegerField(choices=[(-1, '未设置'), (1, '木工'), (2, '泥瓦工')], default=-1, verbose_name='工种')),
                ('completedNeed', models.CharField(max_length=500, null=True, verbose_name='已完成需求')),
                ('ingNeed', models.CharField(max_length=500, null=True, verbose_name='进行中需求')),
            ],
        ),
    ]
