# Generated by Django 2.2.7 on 2019-11-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='password',
            field=models.CharField(max_length=5000, verbose_name='企业密码'),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='password',
            field=models.CharField(max_length=5000, verbose_name='农民工密码'),
        ),
    ]
