# Generated by Django 2.2.7 on 2019-11-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_auto_20191119_1545'),
        ('user', '0003_auto_20191119_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='农民工ID')),
                ('name', models.CharField(max_length=100, verbose_name='农民工姓名')),
                ('IDCard', models.CharField(max_length=100, unique=True, verbose_name='农民工身份证号')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
            ],
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='group',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='authAdvice',
            field=models.CharField(max_length=2000, null=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='enterDes',
            field=models.CharField(max_length=1000, null=True, verbose_name='企业简介'),
        ),
        migrations.AddField(
            model_name='farmers',
            name='ingNeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='needs.Needs', verbose_name='进行中需求'),
        ),
        migrations.AddField(
            model_name='farmers',
            name='memberNumber',
            field=models.IntegerField(default=1, verbose_name='小组人数'),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='IDCard',
            field=models.CharField(max_length=100, null=True, verbose_name='包工头身份证号'),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='包工头ID'),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='包工头用户名'),
        ),
        migrations.DeleteModel(
            name='FarmersGroup',
        ),
        migrations.AddField(
            model_name='farmersmember',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Farmers'),
        ),
    ]
