# Generated by Django 2.2.7 on 2019-11-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_enterprise_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='scope',
            field=models.CharField(max_length=1000, null=True, verbose_name='经营范围'),
        ),
    ]
