# Generated by Django 2.2.7 on 2019-11-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_enterprise_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='包工头ID')),
                ('name', models.CharField(max_length=100, verbose_name='包工头用户名')),
                ('password', models.CharField(max_length=5000, verbose_name='包工头密码')),
                ('openid', models.CharField(max_length=5000, null=True, verbose_name='小程序openid')),
                ('IDCard', models.CharField(max_length=100, null=True, verbose_name='包工头身份证号')),
            ],
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='IDCard',
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='password',
        ),
        migrations.AddField(
            model_name='farmers',
            name='classNumber',
            field=models.IntegerField(default=-1, verbose_name='组号'),
        ),
        migrations.AddField(
            model_name='farmersmember',
            name='authInfo',
            field=models.ImageField(null=True, upload_to='farmerAuth'),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='组ID'),
        ),
        migrations.RemoveField(
            model_name='farmersmember',
            name='group',
        ),
        migrations.AddField(
            model_name='farmersmember',
            name='group',
            field=models.ManyToManyField(null=True, to='user.Farmers'),
        ),
        migrations.AddField(
            model_name='farmers',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Foreman', verbose_name='所属包工头'),
        ),
    ]
