# Generated by Django 2.2.7 on 2019-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191126_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreman',
            name='openid',
            field=models.CharField(default='null', max_length=5000, verbose_name='小程序openid'),
        ),
    ]
