# Generated by Django 2.2.7 on 2019-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191127_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreman',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True, verbose_name='手机号'),
        ),
    ]
