# Generated by Django 2.2.7 on 2019-12-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_foreman_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='authState',
            field=models.CharField(default='未提交', max_length=200, verbose_name='审核状态'),
        ),
    ]
