# Generated by Django 2.2.7 on 2019-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191202_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmersmember',
            name='age',
        ),
        migrations.AddField(
            model_name='farmers',
            name='authState',
            field=models.CharField(default='审核未通过', max_length=2000, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='farmersmember',
            name='phoneNumber',
            field=models.CharField(max_length=100, null=True, verbose_name='手机号'),
        ),
    ]
