# Generated by Django 2.2.7 on 2019-12-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191202_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='authState',
            field=models.CharField(default='审核中', max_length=2000, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='farmersmember',
            name='IDCard',
            field=models.CharField(max_length=100, verbose_name='农民工身份证号'),
        ),
        migrations.RemoveField(
            model_name='farmersmember',
            name='group',
        ),
        migrations.AddField(
            model_name='farmersmember',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Farmers'),
        ),
    ]
