# Generated by Django 2.2.7 on 2019-12-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20191202_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='memberNumber',
            field=models.IntegerField(default=0, verbose_name='小组人数'),
        ),
    ]
