# Generated by Django 2.2.7 on 2019-12-09 07:47

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20191205_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='icon',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='businessItemInsurance',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='商业项目保险'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='businessLicense',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='营业执照'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='constructionPermit',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='施工许可证'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='constructionQUAL',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='建筑资质'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='landUseCert',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='土地使用证'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='noTaxExpStatement',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='无纳税异常声明'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='noticeOfBid',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='拟用工项目中标通知书或其他文件'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='nowProject',
            field=models.CharField(max_length=1000, null=True, verbose_name='当前工程'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='planningPermit',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='规划许可证'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='securityLicense',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='安全许可证'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='socialSecurityCert',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='社保缴费证明'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='startReport',
            field=models.FileField(null=True, upload_to=user.models.enter_auth_file, verbose_name='开工报告'),
        ),
    ]
