# Generated by Django 2.2.7 on 2020-02-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200205_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='contractType',
            field=models.IntegerField(default=0, verbose_name='合同状态'),
        ),
    ]
