# Generated by Django 2.2.7 on 2020-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_farmers_contracttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='phoneNumber',
            field=models.CharField(max_length=1000, null=True, verbose_name='手机号'),
        ),
    ]
