# Generated by Django 2.2.7 on 2019-11-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='需求ID')),
                ('needsDes', models.CharField(max_length=500, null=True, verbose_name='需求描述')),
                ('needsFarmerType', models.CharField(max_length=1000, null=True, verbose_name='所需工种')),
                ('needsNum', models.CharField(max_length=500, null=True, verbose_name='所需工种人员')),
                ('matchResult', models.CharField(max_length=1000, null=True, verbose_name='匹配结果')),
                ('price', models.IntegerField(default=-1, verbose_name='价格')),
                ('needsTime', models.CharField(max_length=500, null=True, verbose_name='时间')),
                ('needsLocation', models.CharField(max_length=1000, null=True, verbose_name='地点')),
                ('needsType', models.IntegerField(choices=[(-1, '未设置'), (1, '编辑中'), (2, '审核中'), (3, '已通过'), (4, '未通过')], default=-1, verbose_name='需求状态')),
                ('enterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Enterprise', verbose_name='企业ID')),
            ],
        ),
    ]
