# Generated by Django 2.2.7 on 2019-11-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needs',
            name='matchResult',
        ),
    ]
