# Generated by Django 2.2.7 on 2019-11-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191119_1117'),
        ('needs', '0002_remove_needs_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='needs',
            name='matchResult',
            field=models.ManyToManyField(to='user.FarmersGroup', verbose_name='匹配结果人员'),
        ),
    ]
