# Generated by Django 2.2.7 on 2019-11-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0003_needs_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='needs',
            name='needsDayNum',
            field=models.IntegerField(default=0, verbose_name='工期'),
        ),
        migrations.AddField(
            model_name='needs',
            name='remarks',
            field=models.CharField(max_length=2000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='enterId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Enterprise', verbose_name='企业ID'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='matchResult',
            field=models.ManyToManyField(to='user.Farmers', verbose_name='匹配结果人员'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsFarmerType',
            field=models.IntegerField(choices=[(-1, '未设置'), (1, '木工'), (2, '泥瓦工')], null=True, verbose_name='所需工种'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsLocation',
            field=models.CharField(max_length=1000, null=True, verbose_name='工地'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsNum',
            field=models.IntegerField(default=0, verbose_name='所需工种人员数'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsTime',
            field=models.DateTimeField(null=True, verbose_name='开工时间'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsType',
            field=models.IntegerField(choices=[(-1, '未设置'), (1, '编辑中'), (2, '匹配中'), (3, '匹配完成待交易'), (4, '交易失败')], default=-1, verbose_name='需求状态'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='price',
            field=models.IntegerField(default=-1, verbose_name='工资'),
        ),
    ]
