# Generated by Django 2.2.7 on 2019-11-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_auto_20191119_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needs',
            name='needsDayNum',
        ),
        migrations.AddField(
            model_name='needs',
            name='needsBeginTime',
            field=models.DateTimeField(null=True, verbose_name='开工时间'),
        ),
        migrations.AddField(
            model_name='needs',
            name='needsEndTime',
            field=models.DateTimeField(null=True, verbose_name='截止时间'),
        ),
        migrations.AddField(
            model_name='needs',
            name='nowNum',
            field=models.IntegerField(default=0, verbose_name='目前人数'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='需求创建时间'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsType',
            field=models.IntegerField(choices=[(-1, '未设置'), (1, '编辑中'), (2, '匹配中'), (3, '匹配完成待支付'), (4, '匹配失败')], default=-1, verbose_name='需求状态'),
        ),
    ]
