# Generated by Django 2.2.7 on 2019-11-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0005_auto_20191125_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needs',
            old_name='enterId',
            new_name='enter',
        ),
    ]
