# Generated by Django 2.2.7 on 2019-11-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0006_auto_20191127_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needs',
            old_name='enter',
            new_name='enterId',
        ),
    ]
