# Generated by Django 2.2.7 on 2019-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0007_auto_20191127_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='needsFarmerType',
            field=models.CharField(default='未设置', max_length=2000, null=True, verbose_name='所需工种'),
        ),
    ]
