# Generated by Django 2.2.7 on 2019-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0008_auto_20191127_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='matchResult',
            field=models.ManyToManyField(null=True, to='user.Farmers', verbose_name='匹配结果人员'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsFarmerType',
            field=models.CharField(max_length=2000, null=True, verbose_name='所需工种'),
        ),
    ]
