# Generated by Django 2.2.7 on 2019-12-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0009_auto_20191129_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='needsType',
            field=models.CharField(default='未设置', max_length=200, verbose_name='需求状态'),
        ),
    ]
