# Generated by Django 2.2.7 on 2019-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0010_auto_20191202_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='needsBeginTime',
            field=models.DateField(null=True, verbose_name='开工时间'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsEndTime',
            field=models.DateField(null=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='needsTime',
            field=models.DateField(auto_now_add=True, verbose_name='需求创建时间'),
        ),
    ]
