# Generated by Django 2.2.7 on 2020-02-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0011_auto_20191202_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='needs',
            name='contractTime',
            field=models.DateField(null=True, verbose_name='合同生成时间'),
        ),
    ]
