# Generated by Django 2.2.7 on 2020-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0012_needs_contracttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='needs',
            name='contractType',
            field=models.IntegerField(default=0, null=True, verbose_name='合同是否确认'),
        ),
    ]
