# Generated by Django 2.2.7 on 2019-11-19 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191119_1117'),
        ('needs', '0003_needs_matchresult'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='beginTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='farmers',
            field=models.ManyToManyField(to='user.Farmers'),
        ),
        migrations.AddField(
            model_name='order',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='needId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='needs.Needs', verbose_name='此订单所属需求'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '交易中'), (2, '已完成'), (3, '已取消')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='000', max_length=200, primary_key=True, serialize=False, verbose_name='订单流水号'),
        ),
    ]
