# Generated by Django 2.2.7 on 2019-11-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191119_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moneyToApp',
            field=models.IntegerField(default=0, verbose_name='给软件金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='moneyToFarmers',
            field=models.IntegerField(default=0, verbose_name='给农工金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='farmers',
            field=models.ManyToManyField(to='user.Farmers', verbose_name='包工头'),
        ),
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.IntegerField(default=0, verbose_name='总交易金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='needId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.Needs', verbose_name='此订单所属需求'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '交易中'), (2, '已完成'), (3, '已取消')], default=1, verbose_name='订单状态'),
        ),
    ]
