# Generated by Django 2.2.7 on 2019-11-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191119_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='farmers',
            field=models.ManyToManyField(to='user.Farmers', verbose_name='组'),
        ),
    ]
