# Generated by Django 2.2.7 on 2019-12-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0016_auto_20191209_1547'),
        ('needs', '0011_auto_20191202_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('p_id', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='订单序号')),
                ('id', models.CharField(default='000', max_length=1000, verbose_name='订单流水号')),
                ('money', models.FloatField(default=0, verbose_name='总交易金额')),
                ('moneyToFarmers', models.FloatField(default=0, verbose_name='给农工金额')),
                ('moneyToApp', models.FloatField(default=0, verbose_name='给软件金额')),
                ('beginTime', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='交易中', max_length=200)),
                ('farmers', models.ManyToManyField(to='user.Farmers', verbose_name='组')),
                ('needId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.Needs', verbose_name='此订单所属需求')),
            ],
        ),
    ]
